#!/bin/bash

SCRIPT_DIR="$(dirname "$0")"
# python "$SCRIPT_DIR/run_experiment.py" --model-name "unsloth/Mistral-Nemo-Instruct-2407-bnb-4bit" --problem-type decision_tree --dataset-base-path "data/datasets/decision_trees_v8/n_inputs_2_depth_4" --dataset-id 0 --response-modes decision explanation --train-set-size 500 --test-set-size 50 --batch-size 16

python "$SCRIPT_DIR/run_experiment.py" --model-name "unsloth/Mistral-Nemo-Instruct-2407-bnb-4bit" --problem-type decision_tree --dataset-base-path "data/datasets/decision_trees_v8/n_inputs_3_depth_5" --dataset-id 0 --response-modes decision explanation --train-set-size 100 --test-set-size 100 --batch-size 16 --output-dir-path-prefix "outputs/experiment"
python "$SCRIPT_DIR/run_experiment.py" --model-name "unsloth/Mistral-Nemo-Instruct-2407-bnb-4bit" --problem-type decision_tree --dataset-base-path "data/datasets/decision_trees_v8/n_inputs_3_depth_5" --dataset-id 0 --response-modes decision explanation --train-set-size 1000 --test-set-size 100 --batch-size 16 --output-dir-path-prefix "outputs/experiment"
python "$SCRIPT_DIR/run_experiment.py" --model-name "unsloth/Mistral-Nemo-Instruct-2407-bnb-4bit" --problem-type decision_tree --dataset-base-path "data/datasets/decision_trees_v8/n_inputs_3_depth_5" --dataset-id 0 --response-modes decision explanation reasoning --train-set-size 100 --test-set-size 100 --batch-size 16 --output-dir-path-prefix "outputs/experiment"
python "$SCRIPT_DIR/run_experiment.py" --model-name "unsloth/Mistral-Nemo-Instruct-2407-bnb-4bit" --problem-type decision_tree --dataset-base-path "data/datasets/decision_trees_v8/n_inputs_3_depth_5" --dataset-id 0 --response-modes decision explanation reasoning --train-set-size 1000 --test-set-size 100 --batch-size 16 --output-dir-path-prefix "outputs/experiment"

python "$SCRIPT_DIR/run_experiment.py" --model-name "unsloth/Mistral-Nemo-Instruct-2407-bnb-4bit" --problem-type logistic_regressor --dataset-base-path "data/datasets/logistic_regressors_v1/n_inputs_5" --dataset-id 0 --response-modes decision explanation --train-set-size 100 --test-set-size 100 --batch-size 16 --output-dir-path-prefix "outputs/experiment"
python "$SCRIPT_DIR/run_experiment.py" --model-name "unsloth/Mistral-Nemo-Instruct-2407-bnb-4bit" --problem-type logistic_regressor --dataset-base-path "data/datasets/logistic_regressors_v1/n_inputs_5" --dataset-id 0 --response-modes decision explanation --train-set-size 1000 --test-set-size 100 --batch-size 16 --output-dir-path-prefix "outputs/experiment"
python "$SCRIPT_DIR/run_experiment.py" --model-name "unsloth/Mistral-Nemo-Instruct-2407-bnb-4bit" --problem-type logistic_regressor --dataset-base-path "data/datasets/logistic_regressors_v1/n_inputs_5" --dataset-id 0 --response-modes decision explanation reasoning --train-set-size 100 --test-set-size 100 --batch-size 16 --output-dir-path-prefix "outputs/experiment"
python "$SCRIPT_DIR/run_experiment.py" --model-name "unsloth/Mistral-Nemo-Instruct-2407-bnb-4bit" --problem-type logistic_regressor --dataset-base-path "data/datasets/logistic_regressors_v1/n_inputs_5" --dataset-id 0 --response-modes decision explanation reasoning --train-set-size 1000 --test-set-size 100 --batch-size 16 --output-dir-path-prefix "outputs/experiment"
